# Generated by Django 4.2.4 on 2023-08-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"verbose_name": "Измерение", "verbose_name_plural": "Измерения"},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"verbose_name": "Датчик", "verbose_name_plural": "Датчики"},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurement",
                to="measurement.sensor",
                verbose_name="Датчик",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Температура"
            ),
        ),
    ]
